apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metric-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "metric-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metric-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metric-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if and .Values.imagePullSecrets .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets.secrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
