# ghcr-pull-secret.yaml
{{- if .Values.imagePullSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret # SealedSecret 타입으로 정의
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.imagePullSecret.sealedDockerConfigJson | quote }} # values.yaml에서 암호화된 값 참조
  template: # Secret 복호화 시 생성될 일반 Secret의 템플릿
    metadata:
      name: {{ .Values.imagePullSecret.name }}
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
