# =================================================================
# Global Settings
# =================================================================
namespace: kubewatch-dev
imagePullSecret:
  enabled: true
  name: ghcr-pull-secret
  encryptedData:
    .dockerconfigjson: {{ .Values.imagePullSecret.sealedDockerConfigJson }}

# =================================================================
# Backend (Flask + SocketIO) Settings
# =================================================================
backend:
  replicaCount: 1
  image:
    repository: ghcr.io/devopslabs-jcg/kubewatch-backend # CI에서 빌드할 새 이미지 이름
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP # 백엔드는 외부로 직접 노출할 필요 없으므로 ClusterIP 사용
    port: 5000
    targetPort: 5000

  serviceAccount:
    create: true
    name: kubewatch-sa # K8s API 접근 권한을 위한 서비스 어카운트

  resources: {}

# =================================================================
# Frontend (React + Nginx) Settings
# =================================================================
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/devopslabs-jcg/kubewatch-frontend # CI에서 빌드할 새 이미지 이름
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80 # 클러스터 내부에서 서비스가 사용할 포트
    targetPort: 80 # 프론트엔드 컨테이너(Nginx)가 노출하는 포트
    nodePort: 30160 # 요청하신 고정 포트

  resources: {}
