# App of Apps 패턴을 구현하는 최종 ApplicationSet 리소스입니다.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-app-manager
  namespace: argocd
spec:
  project: default
  
  # Generator: 어떤 규칙으로 하위 Application을 생성할지 정의합니다.
  generators:
  - git:
      repoURL: https://github.com/devopslabs-jcg/k8s-gitops-configs.git
      revision: main
      # [수정] 이제 모든 기능별 디렉토리를 스캔하도록 설정합니다.
      directories:
      - path: argocd-apps/apps
      - path: argocd-apps/core
      - path: argocd-apps/logging
      - path: argocd-apps/monitoring
      
  # Template: 찾은 디렉토리들을 기반으로 Application을 어떻게 만들지 정의하는 '설계도'입니다.
  template:
    metadata:
      # {{path.basename}}은 찾은 디렉토리 이름(apps, core 등)을 Application 이름으로 사용합니다.
      name: '{{path.basename}}'
      namespace: 'argocd'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/devopslabs-jcg/k8s-gitops-configs.git
        targetRevision: main
        # 각 Application은 해당 디렉토리 경로 하위의 모든 YAML을 관리하게 됩니다.
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

