apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-app-helm # Argo CD UI에 표시될 애플리케이션 이름
  namespace: argocd   # Argo CD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/devopslabs-jcg/k8s-gitops-configs.git
    targetRevision: HEAD
    path: k8s-app-helm-charts/metric-app # Helm Chart 경로
  destination:
    server: https://kubernetes.default.svc
    namespace: metric-app-dev # 앱이 배포될 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 네임스페이스가 없으면 생성
