apiVersion: v1
kind: Service
metadata:
  # 이 이름은 frontend의 nginx.conf에서 proxy_pass에 사용한 이름과 일치해야 함.
  name: kubewatch-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: kubewatch-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
