{{- if and .Values.imagePullSecret .Values.imagePullSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.imagePullSecret.sealedDockerConfigJson }}
  template:
    metadata:
      name: {{ .Values.imagePullSecret.name }}
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
