# k8s-gitops-configs/argocd-apps/logging/kibana-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana # Argo CD UI에서 보여질 애플리케이션 이름
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devopslabs-jcg/k8s-logging-configs.git # k8s-logging-configs Git 리포지토리 URL
    targetRevision: HEAD
    path: helm-values
    helm:
      valueFiles:
        - kibana-values.yaml # k8s-logging-configs/helm-values/kibana-values.yaml 파일을 참조
  destination:
    server: https://kubernetes.default.svc
    namespace: logging # Kibana가 배포될 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    dependsOn: # Elasticsearch가 먼저 배포되도록 의존성 설정 (Kibana는 Elasticsearch에 의존)
      - name: elasticsearch
        namespace: argocd # elasticsearch Argo CD 앱이 있는 네임스페이스 (일반적으로 argocd)
