replicaCount: 1

namespace: metric-app-dev # Deployment가 배포될 네임스페이스

image:
  repository: ghcr.io/devopslabs-jcg/k8s-metric-app # 실제 GHCR 이미지 경로
  tag: latest # 실제 이미지 태그
  pullPolicy: IfNotPresent # 이미지 풀 정책

# resources (컨테이너 리소스 요청/제한)
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP # 또는 NodePort, LoadBalancer 등 원하는 서비스 타입으로 설정
  port: 80 # 컨테이너 포트 (deployment.yaml의 containerPort와 일치시켜야 함)
  targetPort: 5000 # 애플리케이션이 실제로 리스닝하는 포트 (deployment.yaml의 containerPort와 일치시켜야 함)

# imagePullSecrets 정의 (여기에 ghcr-pull-secret 추가)
# 이 리스트는 Deployment 템플릿의 {{- if .Values.imagePullSecrets }} 블록에 사용.
imagePullSecrets:
  - name: ghcr-pull-secret #SealedSecret의 이름
