replicaCount: 1

image:
  repository: ghcr.io/devopslabs-jcg/metric-app
  tag: 5a7e3f05c732f5ea2f4db703ca6ff6ffeae394cb
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80

resources: {}
