replicaCount: 1

namespace: metric-app-dev

image:
  repository: ghcr.io/devopslabs-jcg/k8s-metric-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30100

resources: {}

imagePullSecret:
  enabled: true
  name: ghcr-pull-secret
  # 암호화된 .dockerconfigjson 값은 helm 템플릿에서 SealedSecret에 직접 넣거나,
  # 필요시 여기 선언 후 템플릿에서 참조하도록 구성 가능
  sealedDockerConfigJson: "AgBRx2kdcUn+pvgULLrHWFB5xw2k9Fe5EcF5jejUTE9f8Wp7xj1SOfcXB5CXclkWHkZtr3usjppIx2kxAYF4cN6da6aVgTYVAu4yduKFFApfJgHIxU/hGIxX+qjJSZxr+h+ogNBZfE6U/0zCNxyiVcfJKSJJYtMPvXFmipdJ7XB3KnNQNn4/HCr1YBYTLd7UuYV/LTuaWXhYGEA5IR/p2IuV4eVPoJMR0NsGARfipXTdvkmHgENcf5HBCgVlZDa1ag/ArqxhKWksc/miVO40M0xIV+zjVK6ZBl/qcbpfN71KfDBoVnb4nFowQg1Fzeva/Zk0/87CdOWBSPUp8Zt0qm7CrZvVF4mOFNa88IBrxySt29lRwqZBcNcwOgyvQhw89s1OszvCxHlv4gXFc28ramBOLdCv2QkbnxvKWriPy8nZ8NlDoySSbmlBSkOwCxNtQNyFhXkP51KNSbiGpajdgY+hc/NlTHM5ca/DPZUQjyMRHrt7Vt+28IGAm35zOajg1QpQGvMQuhGTXHYavQDNueWt+Koq20aOYeiQVyrlz2311l9fOy8TGYF2W/OX6ZiUG+kP3i3yK/7veqnQHCLjxMv9df7Y2arqrmHO8gayuNFYu9AUJWDerNnE4PvHKlkzRo77Odhj6x12PdgoCKpCItMPI2TTFZmuJMazXCAfIOQuWTEz4IMNzfMHnXO8tbS7C53xzDl8uZFPfoloMewVJ58jj0nrt2X3+QdTgXqdamY702AtuxgxGfNjD0nkCeA5UFqXCXwFsLsZ/dldzdpAw9MaYWDugQM5NG6+9zTQyFmEFaFxDUx8MNCTzqM7FgMBtW4u3qWg5NNg950yyny3xnS0v+TFiQyTZZAkoddU6L9x4PIKtMruXgRLiDhtr71s2hsM37P4ATm6xL0HMPtuzNjuW1NG+ofz6zNFHUStFpEJTXoe1h4="

serviceAccount:
  create: true
  name: default

