replicaCount: 1

namespace: metric-app-dev

image:
  repository: ghcr.io/devopslabs-jcg/k8s-metric-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources: {}

imagePullSecrets:
  enabled: true
  secrets:
    - name: ghcr-pull-secret

serviceAccount:
  create: true
  name: default
