replicaCount: 1

image:
  repository: ghcr.io/devopslabs-jcg/metric-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80

resources: {}
