apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewatch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/devopslabs-jcg/k8s-gitops-configs.git'
    targetRevision: main
    # [수정] 경로를 metric-app에서 kubewatch로 변경
    path: k8s-app-helm-charts/kubewatch 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubewatch-dev # values.yaml에 정의한 네임스페이스와 일치
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
