---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: kubewatch-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAanj7gClzCEbuLGJw0Y708Ssg8oFW62RRzyG7Ie3dLhRVuaBeMybqgid802WcmUZvT3LmtkS2mvkEBjV/otJ5JcQTINWuvwikqu8PEqs61B/4tjie75UG7QWQq7VY2kMrWcqRDTkS5Az3AZg2pDYdc71/qgtueU5d/8kToHclzNk48azkGYBfF3fpd5toD79Ls52T9GXJRRYhHvV7Fnj06fdAPEqxc8An4Hlz5JjTpKyG1p04piC9rnyUyn6BwDt87LFIdBHrZ1ZTMQWBB8nYmxS8eWqmduVxAuDOQxrIxG9EKaRAqUPWTaYVzdEmJTUo0rijcBAhjs515KEk/8J8kzP2Lak+j7/EfPs0o13cr41OOBoiRu/WmZAr7PsDXk1AQlCpx3DCwiGNrmGikgFPWqfqK7Cw2n8M1oHT72eLvG4ltWpUTDMg7HNilLgVRBAVLKIiPrbsV0hy0d3yTOmKbDeplsRzkVGyElxBcuTGJdTwwN+IXxNP9AwQXz1sRfnj9DeIYrtgvxYWtf0uvEHQLp7dTVTBRvJGsDMKgSc5K6COjS4/iQNFbEgrXkT8haC3oylmM3/S/y4qHO/GieqNv5KKKdN3K7HFyGegLkFOUdeMYhQb1ET7PSNmtbuCb1zUcmDwC1qh3AUvWb94z9kXkIxjpT97WrmFFz9OD3mYKjRXxRhYKEG+5Y23YSlTrE1sOXvqnHLfIybhzFx7IAJwviUROgfQz6QXoU7oRep6813LN402Q4g4/ZS6Z6Xmh7HVn1bEc0tD64d4HVKpMl4z8fPIrWzGJB0hDxrwYju4xpw+N8myrBD90NswzINrGoX6QZChp5jGzxjgx7e9ZyCJqOtek4Ln9kUBL+TLS6oZTUWHpiyJIZZ7Xk5SdyhNaPdqJkkcCrCLu9TBvoywqwMgU5jlTb/fDsodxPw/6
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: kubewatch-dev
    type: kubernetes.io/dockerconfigjson
