---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: metric-app-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB65om37KzOBDLZC9jxkNe2W+qCnvEUaDuSeKU00EAEgbd032jOXedUPeJVk3PibwDuOWbpFlf4pVlMMkaaKvCynsUUg33WvI9hyt/gErUf6TkjWNr1Ydt5pb/rreSZnFzcvb744sBMujioCJ35tKYFxNI0xv5tFAIT0nV7snNrRW6trCwkxYl892VR4bIDSncicNV4x4jmXn8eKCSSBw5aM5GLBzkb2plVCZZecuTErbJbhUxGxfXXXHRnZXAFPwvDf+rORn86Dr8dwKfACPOrhZ0fvGjebFkYI1we8RABZ/wmhf2k3thi3Q7EFq6LVzSVDIyzBI1AKNO3MdUgWSOPj3x31xAk16QMhm7MaDfzVwVLXEPQa+0NFzbdxLSf28vJRWrJSbxEcIgSdxD9C+WCJSS1765UFGMcdJhMuvBKHwvRavhmcuLVLIj34PQkm0z4wCY3/5Tfjl2NB06YlxyHycxOgwHdbi8deI6QlRTtQASF2i8FnHbyU3sRf9e7gMw8yK/YJ4LqLcrlHDXPXjEeZQ5iw9t8+Kx3eYWuuQsd1M2jKd0w2CMjw6LboTh5qY8TJy9HUNsi2w9ZeMRgl3HgqKyWhBvkeJ0nLFGyc/VTaVlxg9C25oFxbVBP2jAO8Un9l4RvTA72h0eFawFXGGHRvCbCZZ3OUnWz39pbOOZu936Z6XCd7GC2+S6Bd6WJNST3U7IQq1XuITVCV1Zx147jFXKQrqz8ooszCAdKJSfTSLDg+6fLE5QX97yjAALXSBia6QfWHTO+9RVVAuALtwGyIYx+qhF47n0EYfJUzihKSV5Y7tCIqnp96N4e/58nnHvUuNuazCSFTNKQ3xUUM82VSxw8VNZQF37Fwn6NV4gYDLAGeVu3UvZtbUEuyxFefZWelhN9QSEIBYvjmJ1wSzrY+TcR5pP+vITkhMPOS1IQd1yiHpg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: metric-app-dev
    type: kubernetes.io/dockerconfigjson
