apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiamFuZ2szNCIsInBhc3N3b3JkIjoiZ2hwX0h5TzBEalNwQWJZNmJvYXZaWFJiWDVFV0xxTWpMNDRSZzFkSyIsImF1dGgiOiJhbUZ1WjJzek5EcG5hSEJmU0hsUE1FUnFVM0JCWWxrMlltOWhkbHBZVW1KWU5VVlhUSEZOYWt3ME5GSm5NV1JMIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: kubewatch-dev
type: kubernetes.io/dockerconfigjson
